runtime: python
env: flex
entrypoint: gunicorn -b :$PORT -k eventlet app:app
runtime_config:
  python_version: 3
manual_scaling:
  instances: 1
# For applications which can take advantage of session affinity
# (where the load balancer will attempt to route multiple connections from
# the same user to the same App Engine instance), uncomment the folowing:
# network:
#   session_affinity: true